apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: s2k
spec:
  integration:
    configuration:
     - type: "secret"
       value: "stage3"
     - type: "configmap"
       value: "stage3-transform"

  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: slack-source
    properties:
      token: "{{secret:stage3/slack.token}}"
      channel:  "{{secret:stage3/slack.channel.name}}"
      delay: 2000

  steps:

  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-sink

  # Filter Slack's Bot messages (messages from other platforms)
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: predicate-filter-action
    properties:
      expression: $.user!='U03NW6H8N5V'
   
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: jslt-action
    properties:
      template: s2k.jslt


  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: room1

  # sink:
  #   ref:
  #     kind: Kamelet
  #     apiVersion: camel.apache.org/v1
  #     name: log-sink    